### ISSUE TITLE
추가할 기능

### ISSUE THREAD

**Issue by CheulSu** [river20s/OMNIBUS#10]
**<오늘의 수확>**
LCD 화면 구성을 성공했습니다! 축하합니다~🎉

**<추가해야 할 기능>**
- ~~특정 시간이 지나면 LCD 초기 화면으로 돌아가기~~
- ~~"해당하는 버스 번호가 없습니다" 등의 처리 TTS 음성 추가하기.~~ lcd 화면에도 문구가 추가되면 좋다(일단은 영문으로...)

<추가하면 좋을 것 같은 기능..?>
- 버튼을 누르고 사용자의 대기가 길어지면 초기로 돌아가기(음성이 추가되면 좋다. "처음으로 돌아갑니다")
- ~~사용자의 음성을 제대로 인식했는지 알기 위해 자연어 처리 되기 전, 사용자의 음성을 확인차 말해주면 좋을 것 같다. (ex. 사용자: 시청역, 기기: 시청역으로 가는 버스 번호를 조회합니다)~~

**Comment by river20s** [comment]
> 사용자의 음성을 제대로 인식했는지 알기 위해 자연어 처리 되기 전, 사용자의 음성을 확인차 말해주면 좋을 것 같다. (ex. 사용자: 시청역, 기기: 시청역으로 가는 버스 번호를 조회합니다)

너무너무 좋은 아이디어 입니다!!!

**Comment by hana021800** [comment]
r

**Comment by hana021800** [comment]
r

**Comment by river20s** [comment]
여러 개의 작업들로 나눈 다음 이슈들 등록해주세욥 @hana021800
