### ISSUE TITLE
시연 (11/21) 전에 미리 준비해야 하는 물건 목록을 정리해 주세요.

### ISSUE THREAD

**Issue by river20s** [river20s/OMNIBUS#11]
# 할일
- 시연 전에 미리 준비해야 하는 물건 목록을 정리해 주세요.
- 팀원 중 갖고 있는 사람이 있다면, 누가 가져올 것인지 정리해야 합니다.
- 만약 구매해야 한다면 어디에서 누가 얼마에 구매할 것인지 의논해야 합니다.
- 우리 팀 회의 구글시트에 새 탭으로 만들어 정리하면 좋을 것 같습니다.
- 아래 내용을 참고해서 정리해주세요.

# 시연 시나리오
## 요구사항
![image](https://github.com/user-attachments/assets/ef82b949-cdd2-4648-8a63-ee924f681574)
## 시연 준비
![image](https://github.com/user-attachments/assets/c6d75731-d417-47a3-90c0-44d0eee95fc3)

**Comment by suyang-2024** [comment]
✋
