### ISSUE TITLE
시연을 위해 필요한 작업 목록을 정리해주세요.

### ISSUE THREAD

**Issue by river20s** [river20s/OMNIBUS#12]
# TODO
- 시연을 위해 필요한 작업 목록을 정리해주세요. 
- 누가, 무엇을, 어떻게, 언제까지 해야 하는지 정리해주세요.
- 팀 노션 혹은 구글시트에 정리해주세요.
- 구체적인 내용은 중간 개발 보고서를 참고해주세요.

**Comment by river20s** [comment]
구글 시트에 `시연할일`이라는 시트로 만들었는데 추가할 작업 있을지 확인 부탁합니다 @Subin-Lim @hana021800 @CheulSu @suyang-2024

**Comment by suyang-2024** [comment]
문서 작업 후 노션의 공지란에 업로드했습니다.
