### ISSUE TITLE
API 키 갱신하기

### ISSUE THREAD

**Issue by river20s** [river20s/OMNIBUS#6]
**10월 30일 이전까지 Google API 키를 갱신해주세요!!**

**Comment by hana021800** [comment]
yup

**Comment by river20s** [comment]
키는 제가 발급 받았고, 라즈베리파이 안에서 새로운 키로 바꿔서 돌려볼 예정입니닷.

**Comment by river20s** [comment]
성공!!! 고마워요 @suyang-2024
