### ISSUE TITLE
의도가 '버스 노선 검색'이 아닌 경우의 안내를 추가해주세요

### ISSUE THREAD

**Issue by river20s** [river20s/OMNIBUS#8]
의도 파악 과정에서 사용자의 의도가 '버스 노선 검색'이 아닌 경우 (예: 안녕하세요.)
적절한 작업을 유도할 수 있게끔 안내 음성을 추가해야 할 것 같습니다.
예시: 원하는 목적지를 말해주세요.
또는 처음으로 돌아가서 목적지를 말할 수 있게끔 해야 합니다.

**Comment by CheulSu** [comment]
헉 마침 찾아놨었는데 화면 구성 알고리즘 구현되면 빠르게 추가하도록 하겠습니다!

**Comment by river20s** [comment]
> 헉 마침 찾아놨었는데 화면 구성 알고리즘 구현되면 빠르게 추가하도록 하겠습니다!

좋습니다!

**Comment by CheulSu** [comment]
😆
TTS 출력 코드 추가하여 "집에 가고싶어" 등의 목적지가 아닌 경우 "목적지를 찾지 못했습니다. 다시 말씀해주세요." 같은 음성 문장이 출력된다.
